### ISSUE TITLE
Click/drag not working in multiplayer; possible mod conflict

### ISSUE THREAD

**Issue by Raevyn-Darke** [Inurosen/OmniPainter-TModLoader#8]
My spouse and I play on our own server. I am able to use OmniPainter fine when only I am online. But when we both are on, I can choose paint but not actually click/select tiles to paint, and nothing happens. In hopes of capturing the issue, we rebooted the server, both joined, I tried to paint, and we both quit out. Hopefully this is helpful. Thanks!

[client.log](https://github.com/Inurosen/OmniPainter-TModLoader/files/15032163/client.log)
[TML server.log](https://github.com/Inurosen/OmniPainter-TModLoader/files/15032185/TML.server.log)

**Comment by Inurosen** [comment]
Fixed in 1.2.2
